export enum Machines {
  /** Maquinas de coser */
  PLANA = 'plana',
  COLLARIN = 'collarin',
  TRIPLE_TRANSPORTE = 'triple-transporte',
  FILETEADORA = 'fileteadora',
  DOS_AGUJAS = 'dos-agujas',
  DE_POSTE = 'de-poste',
  PLANA_MECATRONICA = 'plana-mecatronica',
  FILETEADORA_MECATRONICA = 'fileteadora-mecatronica',
  COLLARIN_MECATRONICA = 'collarin-mecatronica',
  PLANA_ELECTRONICA = 'plana-electronica',
  FILETEADORA_ELECTRONICA = 'fileteadora-electronica',
  COLLARIN_ELECTRONICA = 'collarin-electronica',
  RIBETEADORA = 'ribeteadora',
  PRESILLADORA = 'presilladora',
  CERRADORA = 'cerradora',
  EMPRETINADORA = 'empretinadora',
  BOTONADORA = 'botonadora',
  BORDADORA = 'estampadora',
  MAQUINA_20U = 'maquina-20u',
  ZIG_ZAG = 'zig-zag',
  MULTI_AGUJAS = 'multi-agujas',

  /** Maquina de cortar */
  CORTADORA_BANANA = 'cortadora-banana',
  CORTADORA_CIRCULAR = 'cortadora-circular',
  CORTADORA_INDUSTRIAL = 'cortadora-industrial',
  CUCHILLA_DE_CORTE = 'cuchilla-de-corte',
}
